### ISSUE TITLE
How to avoid extra rerender?

### ISSUE THREAD

**Issue by xiaoyu-tamu** [react-spring/jotai#26]
with Jotai, the `<FakeCard />` will re-render whenever editId changed, but Recoil.js does not because i can select only setter function. How to achieve the same behavior with Jotai? 

## Recoil
```
import React from 'react';
import { atom, useRecoilState, useSetRecoilState } from 'recoil';

const editIdAtom = atom<number | null>({
  key: `editIdAtom`,
  default: null,
});

function FakeCard() {
  const setEditId = useSetRecoilState(editIdAtom);
  const handleClick = React.useCallback(
    (e: React.MouseEvent<HTMLAnchorElement>) => {
      setEditId(1);
    },
    [setEditId]
  );
  return (
    <div>
      <a onClick={handleClick}>toggle</a>
      <FakeModal />
    </div>
  );
}

function FakeModal() {
  const [editId, setEditId] = useRecoilState(editIdAtom);
  const handleClose = React.useCallback(() => {
    setEditId(null);
  }, [setEditId]);

  return editId ? <span>editing {editId}</span> : null;
}
```

## Jotai
```
import React from 'react';
import { atom, useAtom } from 'jotai';

const editIdAtom = atom<number | null>(null);

function FakeCard() {
  const [,setEditId] = useAtom(editIdAtom);
  const handleClick = React.useCallback(
    (e: React.MouseEvent<HTMLAnchorElement>) => {
      setEditId(1);
    },
    [setEditId]
  );
  return (
    <div>
      <a onClick={handleClick}>toggle</a>
      <FakeModal />
    </div>
  );
}

function FakeModal() {
  const [editId, setEditId] = useAtom(editIdAtom);
  const handleClose = React.useCallback(() => {
    setEditId(null);
  }, [setEditId]);

  return editId ? <span>editing {editId}</span> : null;
}
```

**Comment by dai-shi** [comment]
Hi, thanks for opening up the issue.
Jotai core doesn't provide `useSetRecoilState` equivalent. Instead, we use write-only atoms.

```ts
const editIdAtom = atom<number | null>(null);
const setEditIdAtom = atom(null, (_get, set, x: number) => set(editIdAtom, x));

  const [,setEditId] = useAtom(setEditIdAtom);
```

----
Now, I wonder if we can build a generalized hook.
```js
const useSetAtom = (anAtom) => {
  const writeOnlyAtom = useMemo(() => atom(null, (get, set, x) => set(anAtom, x)), [anAtom]);
  return useAtom(writeOnlyAtom)[1];
};
```

**Comment by cevr** [comment]
I think a set of utility hooks for common patterns (like the one mentioned above) would add that icing on top of a wonderful cake

**Comment by dai-shi** [comment]
@cevr Yeah, I agree. And, I want to separate them from the core. Let me start with this one.

The utility hooks can get big. I need someone volunteer to help it, especially for documentation & examples.

**Comment by dai-shi** [comment]
https://www.npmjs.com/package/jotai/v/0.5.0 published which includes #35 
Please report if any issue is found. Closing this.

**Comment by liby** [comment]
```
const editIdAtom = atom<number | null>(null);
const setEditIdAtom = atom(null, (_get, set, x: number) => set(editIdAtom, x));

const [,setEditId] = useAtom(setEditIdAtom);
```
I have two questions about this part of the code:
1.  Writing it this way does not avoid extra rerender, so what is the point?
2. How does it differ from using `const [, setEditId] = useAtom(editIdAtom);` directly?

Looking forward to your reply

**Comment by dai-shi** [comment]
I don't know why you think it doesn't avoid extra rerenders, but here's the example:
https://codesandbox.io/s/empty-wildflower-6kcmf?file=/src/App.js

**Comment by liby** [comment]
@dai-shi 
It should be a problem with the code I wrote during testing, causing me to have the wrong perception. I apologize for asking a question without verifying it. Thank you for correcting me.

**Comment by liby** [comment]
@dai-shi
Follow up report, the reason for my misunderstanding is that not removing primitive atoms when using write-only atoms within a component. 
Example: https://codesandbox.io/s/vigilant-hertz-bqb0r

**Comment by lili21** [comment]
is there any different between `useSetAtom` and `useUpdateAtom` ？

**Comment by dai-shi** [comment]
No. 😁 
https://github.com/pmndrs/jotai/blob/84802077db94ee8874a7e61422e47662d6db7ed6/src/utils.ts#L2
