### ISSUE TITLE
Atoms value updates do not get propagated to transitively dependent atoms

### ISSUE THREAD

**Issue by Shiroy** [react-spring/jotai#30]
Hello,

I encounter an issue with the following snippet:
```typescript
const value = atom(1)
const double = atom(get => get(value) * 2)
const triple = atom(get => get(double) * 3)

// Dependency chain
// triple --(depends on)--> double --(depends on)--> value
```

### Observed behaviour

When I update `value`, `double` is updated as well but `triple` is not. `triple` is updated only after a second render. The following snippet explain the sequence:
``` text
//Initial state
value => 1
double => 2
triple => 6

// value <= 2
value => 2
double => 4
triple => 6

// Another event cause the component to re-render
value => 2
double => 4
type => 12
```

### Expected behaviour

I would expect the snippet above to work as:

``` text
//Initial state
value => 1
double => 2
triple => 6

// value <= 2
value => 2
double => 4
triple => 12
```

It seems that level > 1 dependency relationships between atoms are not handled well.

**Comment by dai-shi** [comment]
Hi! Nice catch! Must be a bug. We'd need to write a failing test.

**Comment by dai-shi** [comment]
@Shiroy It's fixed! Thanks for reporting!
