### ISSUE TITLE
Support reducers for primitive atoms

### ISSUE THREAD

**Issue by dwelle** [react-spring/jotai#38]
Allow primitive atoms to define reducers (setters), which will allow to transform the update. I don't think you should need to create a pair of a primitive and a derived atoms (where you don't export the primitive atom at all) just to accomplish this.

It seems it's somewhat supported even now, but it's undocumented and not typed correctly:

```ts
type List = { id: string; value: number }[];
const sortedListAtom = atom<List, List>([], (get, set, update) => {
  return set(
    sortedListAtom,
    update.sort((a, b) => a.value - b.value)
  );
});
```

[Sandbox](https://codesandbox.io/s/jotai-demo-forked-0u8wf?file=/src/App.tsx)

**Use case:** transform updates so that callers don't have to do it themselves in each call site. In the above example, we want to update the list and ensure it's sorted. The updater may be much more complex and you don't want to force (and ensure) consumers do that themselves.

**Comment by dai-shi** [comment]
Yeah, I have that usage in mind.
However, as you said, TS can't infer types because of the context sensitive function.
So, I left it as an undocumented feature.

> I don't think you should need to create a pair of a primitive and a derived atoms

Creating a pair of atoms was actually my suggestion. #6 

```js
const reducerAtom = (initialValue, reducer) => {
  const pAtom = atom(initialValue)
  return atom(
    get => get(pAtom),
    (get, set, action) => set(pAtom, reducer(get(pAtom), action))
  )
}
```

Still, you may not be happy with this.

It might be just a documentation issue.

**Comment by dai-shi** [comment]
Wait, if it's just a typing issue, can we do this:

```ts
const reducerAtom = <Value, Action>(initialValue: Value, reducer: (v: Value, a: Action) => Value) => {
  const anAtom = atom<Value, Action>(
    initialValue,
    (get, set, action) => set(anAtom, reducer(get(anAtom), action))
  )
  return theAtom
}
```

**Comment by dwelle** [comment]
> Wait, if it's just a typing issue, can we do this:
> 
> ```ts
> const reducerAtom = <Value, Action>(initialValue: Value, reducer: (v: Value, a: Action) => Value) => {
>   const anAtom = atom<Value, Action>(
>     initialValue,
>     (get, set, action) => set(anAtom, reducer(get(anAtom), action))
>   )
>   return theAtom
> }
> ```

It should be typed as this:

```ts
export declare type NonFunction<T> = T extends Function ? never : T;
export declare type NonPromise<T> = T extends Promise<unknown> ? never : T;

const reducerAtom = <Value, Action>(
  initialValue: NonFunction<NonPromise<Value>>,
  reducer: (v: Value, a: Action) => Value
) => {
  const anAtom = atom<Value, Action>(initialValue, (get, set, action) =>
    set(anAtom, reducer(get(anAtom), action))
  );
  return anAtom as WritableAtom<Value, Action>;
};
```

> However, as you said, TS can't infer types because of the context sensitive function.

I'll check the source later to see if it can be helped.

**Comment by dai-shi** [comment]
> The problem is it unnecessarily creates 2 atoms (on top of making the DX worse).

I agree the extra atom is just an overhead. For DX, if we make `reducerAtom`, it would be just an implementation detail whether it's of 2 atoms or one.

> It should be typed as this

Thanks! Yeah, we need to use `any`. Although I wouldn't add this in core, I'm happy to add in utils. Let me draft a PR.

**Comment by dai-shi** [comment]
> Although I wouldn't add this in core

I might change my mind in the future, if there were a better way.

**Comment by dwelle** [comment]
> Although I wouldn't add this in core

I meant just adding the type (if we manage to fix it --- I haven't looked at it yet). If not, it can indeed live in utils as a helper method.

**Comment by vetrivendhan48** [comment]
I feel like Jotai is going in the wrong direction. We must not mix data and business logics. Many people use reducers for processing business logic and they make it too complex by voilating solid principles.

Instead this unscalable code
`const Counter = () => {
  const [count, dispatch] = useAtom(countReducerAtom);
  return (
    <div>
      {count}
      <button onClick={() => dispatch({ type: "inc" })}>+1</button>
      <button onClick={() => dispatch({ type: "dec" })}>-1</button>
    </div>
  );
};`

We can use simple declarative approach.
`const Counter = () => {
  const atomState = useAtom(countReducerAtom);

// The following business hook is pure and easily testable.
  const {increment, decrement} = useCounter(atomState)
  return (
    <div>
      {count}
      <button onClick={increment}>+1</button>
      <button onClick={decrement}>-1</button>
    </div>
  );
};`

Jotai team please consider this and educate your user to avoid using reducers, store or provider.

The alternate for accessing store state outside can be implemented using the singleton pattern.

**Comment by dai-shi** [comment]
Note that atomWithReducer isn't widely used.
`useAtom` is modeled after `useState`. How would you do with `useState`?
Instead of commenting to old issues, please open a new discussion.

**Comment by vetrivendhan48** [comment]
> Note that atomWithReducer isn't widely used. `useAtom` is modeled after `useState`. How would you do with `useState`? Instead of commenting to old issues, please open a new discussion.

I discussed about the reducer way in Jotai. I got the example snippet from this link https://jotai.org/docs/utilities/reducer.
I will raise a new discussion and explain more details there soon. Thanks.
