### ISSUE TITLE
Focusable atoms (optics for this lib)

### ISSUE THREAD

**Issue by merisbahti** [react-spring/jotai#44]
Hello,

Interesting library! 

Would it be possible for you to provide utilities for using this in conjunction with a optics library? My idea for a pretty nice api would be:

```typescript
const bigAtom: WritableAtom<{myKey: number[]}> = atom({myKey: [1,2,3]})
const focusedAtom: WritableAtom<number> = bigAtom.focus(optic => optic.prop('myKey').index(0))
```

Or even:

```typescript
const bigAtom: WritableAtom<{myKey: 10}> = atom({myKey: 10})
const focusedAtom: WritableAtom<number> = bigAtom.prop('myKey').index(0)
```

The optics library I like is https://github.com/akheron/optics-ts

The idea is that if any of the focused atoms are "set", then the big atom is updated, leading to a update to the focused atom.

**Comment by dai-shi** [comment]
I'm not familiar with a opitc library. (Now, I remember I've heard of "lens")
If we add a property to atom (undocumented behavior), you could do anything.

```js
const atomWithFocus = (initialValue) => {
  const anAtom = atom(initialValue)
  anAtom.focus = (fn) => {
    const lens = fn(O.optic())
    return atom(
      get => O.get(lens)(get(anAtom)),
      (get, set, update) => set(O.set(lens)(get(anAtom)))
    )
  }
  return anAtom
}
```

I'm not sure if this is correct...

**Comment by merisbahti** [comment]
Looks about right (typing it will be interesting, since some optics are ReadOnly, and some are removable).

Thanks, I think this resolves my issue.

**Comment by dai-shi** [comment]
If you make a working version of `atomWithFocus`, please share it here.

**Comment by merisbahti** [comment]
Hey dai-shi, I managed to create a focus function for the special case of `ReadWrite` atoms and only for the optics of kind: `Lens`, `Equivalance` and `Isomorphism`. So no Read-only optics, nor any `Prism` (it is possible, I just wanted to scope this).

So the problem I have is that I have to typecast the value in the getter to `NonPromise<A>` and the value setter to `NonFunction<S>`.


```
export function focus<S, A>(
  atom: jotai.WritableAtom<S, SetStateAction<S>>,
  callback: (
    optic: O.OpticFor<S>,
  ) => O.Lens<S, any, A> | O.Equivalence<S, any, A> | O.Iso<S, any, A>,
): jotai.WritableAtom<A, SetStateAction<A>> {
  const focus = callback(O.optic<S>())
  return jotai.atom(
    (atomGetter) => {
      const value = O.get(focus)(
        atomGetter(atom),
        // How do i remove this typecast?
      ) as NonPromise<A>
      return value
    },
    (get, set, update) => {
      set(atom, (param) => {
        const currentValue = O.get(focus)(param)
        const updatedValue =
          update instanceof Function ? update(currentValue) : update
        const updatedSuperValue = O.set(focus)(updatedValue)(
          param,
          // This typecast is bad too
        ) as NonFunction<S>
        return updatedSuperValue
      })
    },
  )
}
```

Ps. I decided to not add a property to your Atom/WriteAtom type yet, this will be done in a later stage. 


Usage: 
```
const bigAtom = atom({ a: 0, b: 5 })
const focusAAtom = focus(bigAtom, (optic) => optic.prop('a'))
const focusBAtom = focus(bigAtom, (optic) => optic.prop('b'))
```

**Comment by dai-shi** [comment]
Looks cool.

> I decided to not add a property to your Atom/WriteAtom type yet

If this works for you, it's good.

> So the problem I have is that I have to typecast the value in the getter to `NonPromise<A>` and the value setter to `NonFunction<S>`.

It's a bit annoying for me too, when we create utility functions.
If you or someone has a suggestion to improve `jotai.atom` typing, I'd be happy to discuss.

**Comment by merisbahti** [comment]
Still can’t get the types to work for Prisms locally for some reason... it seems that the `NonPromise` type swallows and hides the `undefined` from for example: `NonPromise<A | undefined>` and turns it into just `NonPromise<A>` - which is incorrect since prisms can be ”undefined” or focus on no values.

https://www.npmjs.com/package/jotai-optics
https://github.com/merisbahti/jotai-optics

Thanks for any feedback.

**Comment by dai-shi** [comment]
> it seems that the NonPromise type swallows and hides the undefined from for example

That's unexpected. Can you reproduce it on TypeScript playground?

Honestly, I'm not very happy with the current typings of `atom()`. If there's a better way, we'd like to reconsider. https://github.com/pmndrs/jotai/pull/45#issuecomment-692498439

**Comment by merisbahti** [comment]
After creating the sandbox:

https://codesandbox.io/s/jotai-demo-forked-l2b0g?file=/src/App.tsx

It looks like the types are correct:
When using useAtom on the prism:ed atom, the `value` is `number | undefined` and `setValue` is `SetStateAction<number>` which is correct.

**Comment by vit-valchar** [comment]
@merisbahti your example code
https://codesandbox.io/s/jotai-demo-forked-l2b0g?file=/src/App.tsx
works only if the `superAtom.a` value is set. Since it is an optional field, it can be undefined - when it is, the setValue no longer sets value for the focus. I have to update the whole `superAtom` with `a = 0` and then the setValue starts working.

See edited example:
https://codesandbox.io/s/jotai-demo-forked-3cxugy?file=/src/App.tsx

you have to first click on the init button in order to have the second one working. Am I missing something?

**Comment by merisbahti** [comment]
Nope! I think this is the way it's supposed to work.

If an optional focus (Prism) does not have a value, the setter does nothing. 

According to the `optics-ts` docs (which is used here), here's the explaination of the `optional`:
https://akheron.github.io/optics-ts/reference-mc/#optional

> Create a prism that focuses on the non-undefined subtype of A.

If I've understood it correctly, it means that it only focuses on the non-undefined case - if it's another case, then it does nothing. In this case, it's undefined, so it does nothing!

I hope that was of help, and if I can assist with something else or elborate further, please ask :D
